config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    #home
    root to: 'home#index'
    get '/about', to: 'home#about', as: 'about'
    get '/contact', to: 'home#contact', as: 'contact'
    get '/photos', to: 'home#photos', as: 'photos'
    get '/resume', to: 'home#resume', as: 'resume'
    get '/download_resume', to: "home#download_resume", as: 'download_resume'

    #DEVISE:
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    devise_for :clients, controllers: { registrations: 'client/registrations', sessions: 'client/sessions' }

    devise_for :sellers, controllers: { registrations: 'seller/registrations', sessions: 'seller/sessions' }, path_names: { registration: ENV['NEW_SELLER_PATH'] }

    #DASHBOARDS:
    get "c/:id/dashboard" => 'dashboard_clients#show', as: :client_dashboard
    resources :clients, path: "c", only: [:update, :destroy] do
      resource :basket, only: :edit, path: "checkout"
      resources :basket_lines, only: :update, path: "b"
      resources :locations, only: [:create, :update, :destroy], path: "l"
    end

    get "s/:id/dashboard" => 'dashboard_sellers#show', as: :seller_dashboard
    resources :sellers, path: "s", only: [:update] do
      member { patch 'update_cover'}
      member { patch 'attach_image'}
      member { patch 'delete_image'}
      resources :products, only: [:create, :update, :destroy], path: "p" do
        member { patch 'update_cover'}
        member { patch 'attach_image' }
        member { patch 'delete_image' }
      end
      resources :locations, only: [:create, :update, :destroy], path: "l"
    end

    #CATALOGUE:
    resources :products, only: :show

    get '/catalogue(/:page)', to: 'products#index', as: 'catalogue'
    get '/s/:id(/:page)', to: 'products#index_seller', as: 'c_seller'
    get '/c/:id(/:page)', to: 'products#index_category', as: 'c_category'

    #CHECKOUT
    resources :baskets, only: :show
    resources :basket_lines, only: [:create, :update]

    resources :orders, only: [:create]

    # concern :manageable do
    #   resources :conversations, :orders...
    # end
  end
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :client, required: false
  has_many :basket_lines

  def lines
    basket_lines
  end

  def ordered_lines
    basket_lines.order(:created_at)
  end

    public

    # called from devise after login
    def duplicate_lines(other_basket)
      other_basket.basket_lines.each do |line|
        BasketLine.create(product_id: line.product_id, quantity: line.quantity, basket_id: self.id)
      end
    end

    def set_amount
      amount = 0
      self.basket_lines.each do |line|
        amount += (line.product_price * line.quantity)
      end
      return amount
    end
end

app/controllers/_baskets_controller.rb
class BasketsController < ApplicationController
  # before_action :authenticate_client!
  before_action :set_basket, only: :edit

  # def edit
  #   @lines = @basket.basket_lines
  # end

  private

    def set_basket
      if params[:client_id]
        @basket = Client.friendly.find(params[:client_id]).basket
      else
        @basket = Basket.find(cookies['basket_id'])
      end
    end

    def basket_params
      params.require(:basket).permit(:products, :client_id)
    end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :set_basket, only: :show
  before_action :prepare_order, only: :show

  def show
    @lines = @basket.basket_lines
  end

  private

    def prepare_order
      if current_client
        @order = Order.new(client_id: @basket.client.id, amount: @basket.set_amount)
      else
        @order = Order.new(amount: @basket.set_amount)
      end
    end

    def set_basket
      if current_client
        @basket = current_client.basket
      elsif cookies['basket_id']
        @basket = Basket.find(cookies['basket_id'])
      else
        @basket = Basket.create
        cookies['basket_id'] = @basket.id
      end
    end

    def basket_params
      params.require(:basket).permit(:products, :client_id)
    end
end

app/views/baskets/_basket.html.erb
<div id="basket" class="d-flex justify-content-center p-2 bd-highlight">
  <div id="lines" class="flex-column">
    <%= render partial: 'baskets/edit' %>
  </div>
</div>

<% unless @current_basket.ordered_lines.empty? %>
  <div class="d-flex justify-content-center p-2 bd-highlight">
    <div id="total_price" class="flex-column">
      <em><%= t(:total_amount) %>: </em><%= price(@order.amount) %>
    </div>
  </div>

  <div class="d-flex justify-content-center p-2 bd-highlight">
    <div id="place_order" class="justify-content-center">
      <% if current_client %>
        <%= link_to t(:place_order), orders_path, method: :post, class: "btn btn-primary" %>
      <% else %>
        <%= link_to t(:place_order), new_client_registration_path(origin: "basket"), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/baskets/_edit.html.erb
<% if @current_basket %>
  <ul class="list-group">
    <% @current_basket.ordered_lines.each do |line| %>
      <li class="list-group-item">
        <%= render partial: "products/line", locals: { product: line.product, line: line } %>
      </li>
    <% end %>
  </ul>
<% else %>
  Basket unavailable.
<% end %>
<% if @current_basket.ordered_lines.empty? %>
  <h5><%= t(:empty_basket) %></h5>
<% end %>

app/views/baskets/edit.html.erb
<span>My Basket</span><br/>
<% @basket_lines.each do |line| %>
  <%= render partial: "baskets/item", locals: { line: line, product: line.product } %>
  <%= form_with model: line, url: basket_line_path(line) do |f| %>
    <%= f.hidden_field :product_id, value: line.product.id %>
    <%= f.hidden_field :basket_id, value: line.basket.id %>
    <%= f.hidden_field :quantity, value: 1 %>
    <%= f.submit "Add to basket" %>
  <% end %>
<% end %>
<br/>
<br/>
<br/>
<br/>
<%= @basket.inspect %>
<%= @basket_lines.inspect %>

app/views/baskets/show.html.erb
<%= render 'nav/top' %>

<%= render partial: 'baskets/basket' %>

<%= render 'nav/footer' %>