config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    #home
    root to: 'home#index'
    get '/about', to: 'home#about', as: 'about'
    get '/contact', to: 'home#contact', as: 'contact'
    get '/photos', to: 'home#photos', as: 'photos'
    get '/resume', to: 'home#resume', as: 'resume'
    get '/download_resume', to: "home#download_resume", as: 'download_resume'

    #DEVISE:
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    devise_for :clients, controllers: { registrations: 'client/registrations', sessions: 'client/sessions' }

    devise_for :sellers, controllers: { registrations: 'seller/registrations', sessions: 'seller/sessions' }, path_names: { registration: ENV['NEW_SELLER_PATH'] }

    #DASHBOARDS:
    get "c/:id/dashboard" => 'dashboard_clients#show', as: :client_dashboard
    resources :clients, path: "c", only: [:update, :destroy] do
      resource :basket, only: :edit, path: "checkout"
      resources :basket_lines, only: :update, path: "b"
      resources :locations, only: [:create, :update, :destroy], path: "l"
    end

    get "s/:id/dashboard" => 'dashboard_sellers#show', as: :seller_dashboard
    resources :sellers, path: "s", only: [:update] do
      member { patch 'update_cover'}
      member { patch 'attach_image'}
      member { patch 'delete_image'}
      resources :products, only: [:create, :update, :destroy], path: "p" do
        member { patch 'update_cover'}
        member { patch 'attach_image' }
        member { patch 'delete_image' }
      end
      resources :locations, only: [:create, :update, :destroy], path: "l"
    end

    #CATALOGUE:
    resources :products, only: :show

    get '/catalogue(/:page)', to: 'products#index', as: 'catalogue'
    get '/s/:id(/:page)', to: 'products#index_seller', as: 'c_seller'
    get '/c/:id(/:page)', to: 'products#index_category', as: 'c_category'

    #CHECKOUT
    resources :baskets, only: :show
    resources :basket_lines, only: [:create, :update]

    resources :orders, only: [:create]

    # concern :manageable do
    #   resources :conversations, :orders...
    # end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = get_locale_categories
    @sellers = get_locale_sellers
    @tags = get_locale_tags
  end

  def about
  end

  def contact
  end

  def photos
  end

  def resume
  end

  def download_resume
    send_file "#{Rails.root}/app/assets/images/resume/resume-jc-belouard.pdf", type: "application/pdf", x_sendfile: true
  end
end

app/views/home/_catalogue_links.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h2 class="d-flex justify-content-center">
      <span class="border-bottom border-primary">
        <%= t(:categories).titleize %>
      </span>
    </h2>
    <p class="lead d-flex justify-content-center flex-wrap">
      <%= link_to t(:all), catalogue_path, class: "home-links" %>
      <% @categories.each do |category| %>
        <%= link_to category[0], c_category_path(category[0]), class: "home-links" %>
      <% end %>
    </p>
    <hr class="my-4">
    <h2 class="d-flex justify-content-center">
      <span class="border-bottom border-primary">
        <%= t(:featured_sellers).titleize %>
      </span>
    </h2>
    <p class="lead d-flex justify-content-center flex-wrap">
      <% @sellers.each do |seller| %>
        <%= link_to seller.name, c_seller_path(seller.slug), class: "home-links" %>
      <% end %>
    </p>
    <hr class="my-4">
    <h2 class="d-flex justify-content-center">
      <span class="border-bottom border-primary">
        <%= t(:popular_tags).titleize %>
      </span>
    </h2>
    <p class="lead d-flex justify-content-center flex-wrap">
      <% @tags.each do |tag| %>
        <%= link_to tag, catalogue_path(tag: tag), class: "home-links" %>
      <% end %>
    </p>
  </div>
</div>

app/views/home/_presentation.html.erb
<div class="jumbotron jumbotron-fluid welcome">
  <h1 class="display-4 hue"><%= t(:welcome).capitalize %></h1>
  <p class="lead hue"><%= t(:welcome_text_html) %></p>
</div>

app/views/home/about.html.erb
About page

app/views/home/contact.html.erb
Contact page

app/views/home/index.html.erb
<%= render 'nav/top' %>

<%= render 'home/presentation' %>

<%= render 'home/catalogue_links'%>

<%= render 'nav/footer' %>

app/views/home/photos.html.erb
Food - Photo by Oleg Magni from Pexels
<br/>
Fashion - Photo by Artem Beliaikin from Pexels
<br/>
Book - Photo by Janko Ferlic from Pexels
<br/>
Ciara flowers - Photo by Magda Ehlers from Pexels - www.youtube.com/channel/UCdUKSVdrwwJRssD2LRVYQtQ<br/>

Julie & the sea - Photo by Emiliano Arano from Pexels
<br/>
Lilac book 1 & 2 - Photo by Suzy Hazelwood from Pexels - wordmusing.wordpress.com/<br/>

Lilac book 3 - Photo by Hoang Bin from Pexels
<br/>
Green dress 1 & 2 - Photo by Anne from Pexels - latsbookstore.wordpress.com/<br/>

Green dress 3 - Photo by Moose Photos from Pexels - photos.icons8.com/<br/>

Rose water 1 & 2 - Photo by Izabella Bedő from Pexels - www.facebook.com/BRELL-421032572101846/?modal=admin_todo_
<br/>
Rose water 3 - Photo by Asim Alnamat from Pexels - http://asimalnamat.wixsite.com/asim <br/>

Cupcake book 1 - Photo by Oleg Magni from Pexels
<br/>
Cupcake book 2 - Photo by Acharaporn Kamornboonyarush from Pexels - www.shutterstock.com/g/feelartfeelant?language=en<br/>

Praline cake 1 - Alexander Dummer - www.4dgraphic.de

Praline cake 2 & 3 - Photo by Kristina Paukshtite from Pexels - www.facebook.com/kristina.paukshtite<br/>

Classic apron 1 & 2 - Photo by Anna Guerrero from Pexels
<br/>
Classic apron 3 - Photo by Jeswin Thomas from Pexels
<br/>
Sailor cap 1 - Photo by Caleb Oquendo from Pexels
<br/>
Sailor cap 2 - Photo by VisionPic.net from Pexels - http://visionpic.net<br/>

Sailor cap 3 - Photo by Pedro Sandrini from Pexels - https://www.pedrosandrini.com/<br/>

Arcachon oysters 1 & 2 - Photo by Elle Hughes from Pexels - www.ellehughes.co<br/>

Moby Dick 1 - Photo by Limuel Gonzales from Pexels
<br/>
Moby Dick 2 - Photo by Andre Estevez from Pexels
<br/>
Moby Dick 3 - Photo by Caio Resende from Pexels - instagram.com/res.caio<br/>

app/views/home/resume.html.erb
<div class="d-flex flex-row">
  <%= link_to "Back", :back, class: "back-button" %>
  <%= link_to "Download resume", download_resume_path, class: "download-button" %>
</div>
<%= image_tag "resume/resume-jc-belouard.jpg", class: "resume" %>