config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    #home
    root to: 'home#index'
    get '/about', to: 'home#about', as: 'about'
    get '/contact', to: 'home#contact', as: 'contact'
    get '/photos', to: 'home#photos', as: 'photos'
    get '/resume', to: 'home#resume', as: 'resume'
    get '/download_resume', to: "home#download_resume", as: 'download_resume'

    #DEVISE:
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    devise_for :clients, controllers: { registrations: 'client/registrations', sessions: 'client/sessions' }

    devise_for :sellers, controllers: { registrations: 'seller/registrations', sessions: 'seller/sessions' }, path_names: { registration: ENV['NEW_SELLER_PATH'] }

    #DASHBOARDS:
    get "c/:id/dashboard" => 'dashboard_clients#show', as: :client_dashboard
    resources :clients, path: "c", only: [:update, :destroy] do
      resource :basket, only: :edit, path: "checkout"
      resources :basket_lines, only: :update, path: "b"
      resources :locations, only: [:create, :update, :destroy], path: "l"
    end

    get "s/:id/dashboard" => 'dashboard_sellers#show', as: :seller_dashboard
    resources :sellers, path: "s", only: [:update] do
      member { patch 'update_cover'}
      member { patch 'attach_image'}
      member { patch 'delete_image'}
      resources :products, only: [:create, :update, :destroy], path: "p" do
        member { patch 'update_cover'}
        member { patch 'attach_image' }
        member { patch 'delete_image' }
      end
      resources :locations, only: [:create, :update, :destroy], path: "l"
    end

    #CATALOGUE:
    resources :products, only: :show

    get '/catalogue(/:page)', to: 'products#index', as: 'catalogue'
    get '/s/:id(/:page)', to: 'products#index_seller', as: 'c_seller'
    get '/c/:id(/:page)', to: 'products#index_category', as: 'c_category'

    #CHECKOUT
    resources :baskets, only: :show
    resources :basket_lines, only: [:create, :update]

    resources :orders, only: [:create]

    # concern :manageable do
    #   resources :conversations, :orders...
    # end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :seller
  has_many :product_tags, dependent: :destroy
  has_many :product_translations, dependent: :destroy
  has_many :order_lines
  accepts_nested_attributes_for :product_tags, allow_destroy: true, reject_if: proc { |attributes| attributes['tag'].blank? }
  accepts_nested_attributes_for :product_translations, allow_destroy: true, reject_if: proc { |attributes| attributes['description'].blank? }
  
  has_one_attached :cover, dependent: :destroy
  has_many_attached :images, dependent: :destroy
  validates_with ProductImagesValidator

  extend FriendlyId
  friendly_id :name_and_seller_slug, use: :slugged
  
  def name_and_seller_slug
    "#{name}-#{self.seller.slug}"
  end

  def set_cover_placeholder
    path = Rails.root.join('app', 'assets', 'images', 'placeholders', 'seller-cover.png').to_s
    self.cover.attach(io: File.open(path), filename: 'seller-cover.png')
  end

  def set_images_placeholder
    path = Rails.root.join('app', 'assets', 'images', 'placeholders', 'seller-image.png').to_s
    self.images.attach(io: File.open(path), filename: 'seller-image.png')
  end

  def available_translations
    result = {}
    I18n.available_locales.each do |lang|
      result[lang] = self.translations.include? lang.to_s
    end
    return result
  end

  def prepare_empty_tags
    (ProductTag.max_num_of_tags_per_product - self.product_tags.count).times { self.product_tags.build }
  end

  def prepare_empty_translations
    I18n.non_default_locales_hash.size.times { self.product_translations.build }
  end
  # I18n.non_default_locales_hash in config/initializers/extensions/i18n.rb

  def self.find_by_tag(tag)
    Product.find_by_sql(["SELECT * FROM products WHERE id IN (SELECT product_id FROM product_tags WHERE tag LIKE ?)", tag])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :update, :update_cover, :attach_image, :delete_image, :destroy]
  before_action :set_redirect_path, only: [:create, :update, :update_cover, :attach_image, :delete_image, :destroy]
  before_action :translate_product, only: [:show]
  load_and_authorize_resource :seller, find_by: :slug, only: [:create, :update, :update_cover, :attach_image, :delete_image, :destroy]
  include ProductSql 

  def index
    @namespace = "catalogue"
    get_index_data
  end

  def index_category
    @namespace = "c/" + params['id']
    params['category'] = get_category_id
    redirect_to root_path(params['locale']), alert: "Category not found." and return if params['category'] == "no match"
    @presentee = Category.find(params['category'])
    get_index_data
    presentee_translate
    presentee_placeholder_cover
    render "index"
  end

  def index_seller
    params['seller'] = params['id']
    @namespace = "s/" + params['seller']
    #check if seller exists
    @presentee = Seller.find_by_slug(params['seller'])
    get_index_data
    presentee_translate
    presentee_placeholder_cover
    render "index"
  end

  def show
    @categories = get_locale_categories
    @sellers = get_locale_sellers #.limit(8)
    @tags = get_locale_tags
    @seller = @product.seller
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html do
          redirect_to @redirect_path, notice: 'Product was successfully created.'
        end
        format.json { render :show, status: :created, location: @product }
      else
        format.html { redirect_to @redirect_path, alert: "Product wasn't successfully created" + " " + @product.errors[:image].to_s }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @redirect_path, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { redirect_to @redirect_path, alert: "Product wasn't successfully updated" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_cover
    respond_to do |format|
      if @product.cover = params[:product][:cover]
        format.html do
          redirect_to @redirect_path, notice: 'Cover was successfully updated.'
        end
        format.json { render :show, status: :updated, location: @product }
      else
        format.html { redirect_to @redirect_path, alert: "Cover wasn't successfully updated" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def attach_image
    respond_to do |format|
      if @product.images.attach(params[:product][:image])
        format.html do
          redirect_to @redirect_path, notice: 'Image was successfully added.'
        end
        format.json { render :show, status: :updated, location: @product }
      else
        format.html { redirect_to @redirect_path, alert: "Image wasn't successfully added." }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete_image
    image = ActiveStorage::Attachment.find(params[:product][:image_id])
    respond_to do |format|
      if image.purge
        format.html do
          redirect_to @redirect_path, notice: 'Image was successfully deleted.'
        end
        format.json { render :show, status: :updated, location: @product }
      else
        format.html { redirect_to @redirect_path, alert: "Image wasn't successfully deleted." }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to @redirect_path, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private

    def set_product
      @product = Product.friendly.find(params[:id])
    end
      
    def product_params
      params.require(:product).permit(:id, :name, :slug, :category, :description, :price, :price_excl_vat, :price_discount, :price_discount_excl_vat, :translations, :seller_id, :cover, images: [], product_tags_attributes: [:id, :tag, :lang, :product_id, :_destroy], product_translations_attributes: [:id, :lang, :description, :product_id])
    end

    def set_redirect_path
      @redirect_path = seller_dashboard_path(params["seller_id"])
    end

    def translate_product
      @product = @product.translate_object(params['locale']) unless params['locale'] == I18n.default_locale
    end

    def placeholder_images
      @products.each do |product|
        product.set_cover_placeholder unless product.cover.attached?
        product.set_images_placeholder unless product.images.attached?    
      end
    end

    def presentee_placeholder_cover
      @presentee.set_cover_placeholder unless @presentee.cover.attached?   
    end

    def presentee_translate
      @presentee = @presentee.translate_object(params['locale']) unless params['locale'] == I18n.default_locale.to_s
    end

    def current_ability
      @current_ability ||= ::Ability.new(current_seller)
    end

    def get_index_data
      # toolbar data
      @categories = get_locale_categories
      @sellers = get_locale_sellers #.limit(8)
      @tags = get_locale_tags
      # main content data
      result_hash = ProductSql.get_products(params)
      @products = result_hash[:set]
      # pagination data
      @pages_urls = get_pages_urls(params['locale'], @namespace, request.query_parameters.to_query, params['page'].to_i, result_hash[:max_size])
      placeholder_images
    end

    def get_category_id
      # all_as_hash returns {"en"=>[["Category", 1]...], "fr"=>[["Catégorie", 1]...]}
      match = Category.all_as_hash[params['locale']].select { |cat| cat[0] == params['id'].capitalize }
      if match != []
        match[0][1]
      else
        "no match"
      end
    end
end

app/views/products/_card.html.erb
<div class="card" style="width: 18rem;">
  <%= link_to product_path(product) do %>
    <%= image_tag(url_for(product.cover), class: "card-img-top") %>
    <% product.tags.each_with_index do |tag, i|%>
      <%= link_to "#" + tag, catalogue_path(tag: tag), class: "card-bottom-#{i}" %>
    <% end %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= link_to product.name, product_path(product) %></h5>
    <h6 class="card-subtitle"><%= price(product.price) %></h6>
    <p class="card-text"><%= truncate(product.description, length: 60) %></p>
    <%= form_with model: BasketLine.new, url: basket_lines_path, class: "add-form" do |f| %>
      <%= f.hidden_field :product_id, value: product.id %>
      <%= f.hidden_field :basket_id, value: basket_id %>
      <%= f.submit t(:add), class: "add-submit" %>
      <%= f.number_field :quantity, value: 1, class: "add-number" %>
      <%= f.submit t(:to_basket), class: "add-submit" %>
    <% end %>
  </div>
</div>

app/views/products/_edit.html.erb
<% if product.slug && product.prepare_empty_tags %>

  <div id="<%= product.slug %>-col" class="collapse" data-parent="#content">

  
    <% product_html_id = product.slug.gsub(/-/, "_") %>
    <% display_en = @prod_lang[product.slug][:en] ? "display:inline-flex;" : "display:none;" %>
    <% display_fr = @prod_lang[product.slug][:fr] ? "display:inline-flex;" : "display:none;" %>

    <%= form_with model: product, url: seller_product_path(@seller.slug, product.slug), id: product.slug, html: { class: "form-dashboard d-flex flex-column align-items-start bg-light rounded-lg" } do |f| %>

      <div class="form-group form-dashboard-field">
        <%= f.label :category, t(:category), class: "label-dashboard" %>
        <%= f.select(:category, options_for_select(Category.all_as_hash[params['locale']]), {}, { class: "form-control input-dashboard" }) %>
      </div>
    
      <div class="form-group form-dashboard-field">
        <%= f.label :name, t(:name), class: "label-dashboard" %>
        <%= f.text_field :name, class: "form-control input-dashboard" %>
      </div>

      <div class="form-group form-dashboard-field">
        <%= label_tag :en, t(:available_en), class: "label-dashboard" %>
        <%= check_box_tag product_html_id + "_en", :en, @prod_lang[product.slug][:en], class: "check-dashboard" %>
      </div>

      <div class="form-group form-dashboard-field">
        <%= f.label :description, t(:description_en), class: "label-dashboard" %>
        <%= f.text_field :description, class: "form-control input-dashboard" %>
      </div>

      <% I18n.non_default_locales_hash.each do |sym, string| %>
        <div class="form-group form-dashboard-field">
          <%= label_tag sym, t(:available) + t(string), class: "label-dashboard" %>
          <%= check_box_tag product_html_id + "_" + sym.to_s, sym, @prod_lang[product.slug][sym], class: "check-dashboard" %>
        </div>

        <%= f.fields_for :product_translations do |trans| %>
          <div class="form-group form-dashboard-field">
            <%= trans.label :description, t(:description) + " " + t(string), class: "label-dashboard" %>
            <%= trans.text_field :description, class: "form-control input-dashboard" %>
            <%= trans.hidden_field :lang, value: sym %>
          </div>
        <% end %>
      <% end %>

      <%= f.hidden_field :translations, class: "#{product_html_id}_translations" %>

      <div class="form-group form-dashboard-field">
        <%= f.label :price, t(:price), class: "label-dashboard" %>
        <%= f.text_field :price, class: "form-control input-dashboard" %>
      </div>

      <div class="form-group form-dashboard-field">
        <%= f.label :price_excl_vat, t(:price_excl_vat), class: "label-dashboard" %>
        <%= f.text_field :price_excl_vat, class: "form-control input-dashboard" %>
      </div>

      <div id="<%= product_html_id %>_tags_english" style="<%= display_en %>">
        <div class="form-group d-flex flex-column form-dashboard-field">
          <%= f.fields_for :product_tags do |tags| %>
            <div class="d-flex">
              <%= tags.label :tag, t(:tag) + " " + t(:english), class: "label-dashboard" %>
              <%= tags.text_field :tag, class: "form-control input-dashboard tag-dashboard" %>
              <%= tags.hidden_field :lang, value: "en" %>
            </div>
          <% end %>
        </div>
      </div>
    
      <% I18n.non_default_locales_hash.each do |sym, string| %>
        <div id="<%= product_html_id %>_tags_<%= string %>" style="<%= display_fr %>">
          <div class="form-group d-flex flex-column form-dashboard-field">
            <%= f.fields_for :product_tags do |tags| %>
              <div class="d-flex">
                <%= tags.label :tag, t(:tag) + " " + t(string), class: "label-dashboard" %>
                <%= tags.text_field :tag, class: "form-control input-dashboard tag-dashboard" %>
                <%= tags.hidden_field :lang, value: sym.to_s %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>

      <%= f.hidden_field :seller_id, value: @seller.id %>

      <div class="action submit-dahsboard">
        <%= f.submit "Edit" %>
      </div>
    <% end %>

    <% if product.cover.attached? %>
      <%= form_with model: product, url: update_cover_seller_product_path(@seller.slug, product.slug), id: "product_cover_" + product.slug, html: { class: "form-dashboard d-flex flex-column align-items-start bg-light rounded-lg" } do |af| %>
          
        <div class="form-group form-dashboard-field file-dashboard">
          <%= af.label :cover, t(:cover), class: "label-dashboard" %>
        </div>

        <div class="image-dashboard">
          <%= image_tag(url_for(product.cover), size: "700x300") %>
        </div>

        <div class="form-group form-dashboard-field file-dashboard">
          <%= af.label :cover, t(:replace_with), class: "label-dashboard" %>
          <%= af.file_field :cover %>
        </div>

        <div class="action submit-dahsboard">
          <%= af.submit t(:submit), class: "btn btn-dark" %>
        </div>
      <% end %>
    <% end %>

    <% if product.images.attached? %>
      <div class="form-dashboard d-flex flex-row align-items-start bg-light rounded-lg ">
        <% product.images.each do |i| %>
          <%= form_with model: product, url: delete_image_seller_product_path(@seller.slug, product.slug), id: i.id, class: "del_img" do |af| %>

            <div class="form-group form-dashboard-field file-dashboard">
              <%= af.label :image, t(:image), class: "label-dashboard" %>
            </div>

            <div class="image-dashboard">
              <%= image_tag i, size: "300x200" %>
            </div>

            <%= af.hidden_field :image_id, value: i.id %>

            <div class="action submit-dahsboard">
              <%= af.submit t(:delete), class: "btn btn-danger" %>
            </div>

          <% end %> 
        <% end %>
      </div>
    <% end %>

    <%= form_with model: product, url: attach_image_seller_product_path(@seller.slug, product.slug), id: "new_image_" + product.slug, html: { class: "form-dashboard d-flex flex-column align-items-start bg-light rounded-lg" } do |af| %>

      <div class="form-group form-dashboard-field file-dashboard">
        <%= af.label :image, t(:add_image), class: "label-dashboard" %>
      </div>

      <div class="form-group form-dashboard-field file-dashboard">
        <%= af.file_field :image, multiple: true %>
      </div>

      <div class="action submit-dahsboard">
        <%= af.submit t(:submit), class: "btn btn-dark" %>
      </div>
    <% end %>

    <div class="form-dashboard align-items-start bg-light rounded-lg">
      <div class="action submit-dahsboard">
        <%= link_to t(:remove_product), seller_product_path(@seller.slug, product.slug), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      </div>
    </div>

  </div>

  <script type='text/javascript'>
    var <%= product_html_id %>_en = document.getElementById('<%= product_html_id %>_en'), 
      <%= product_html_id %>_fr = document.getElementById('<%= product_html_id %>_fr'),
      <%= product_html_id %>_hidden = document.getElementsByClassName('<%= product_html_id %>_translations'),
      <%= product_html_id %>_tags_en = document.getElementById('<%= product_html_id %>_tags_english'),
      <%= product_html_id %>_tags_fr = document.getElementById('<%= product_html_id %>_tags_french');

    <%= product_html_id %>_en.addEventListener('change', function() {
      if(this.checked) {
          <%= product_html_id %>_hidden[0].value = <%= product_html_id %>_hidden[0].value += "|en"
          <%= product_html_id %>_tags_en.style.display = 'inline-flex'
      } else {
          <%= product_html_id %>_hidden[0].value = <%= product_html_id %>_hidden[0].value.replace("en", "")
          <%= product_html_id %>_tags_en.style.display = 'none'
      }
    }, false);

    <%= product_html_id %>_fr.addEventListener('change', function() {
      if(this.checked) {
          <%= product_html_id %>_hidden[0].value = <%= product_html_id %>_hidden[0].value += "|fr"
          <%= product_html_id %>_tags_fr.style.display = 'inline-flex'
      } else {
          <%= product_html_id %>_hidden[0].value = <%= product_html_id %>_hidden[0].value.replace("fr", "")
          <%= product_html_id %>_tags_fr.style.display = 'none'
      }
    }, false);
  </script>
<% end %>

app/views/products/_full.html.erb
<% if false %>
<br/>
<%= @product.description %>

<% if @product.images.attached? %>
  <% @product.images.attachments.each do |i| %>
    <%= image_tag(i) %>
  <% end %>
<% end %>
<% end %>
<div class="card product-full bg-light">
  <div class="card-body product-full-body">
    <h2 class="card-title product-full-title rounded"><%= @product.name %></h2>
    <div id="product-carousel" class=" product-carousel carousel slide carousel-fade" data-ride="carousel">
      <div class="carousel-inner">
        <% @product.images.each_with_index do |image, i| %>
          <% active = "active" if i == 0 %>
          <div class="carousel-item <%= active %>">
            <%= image_tag(url_for(image), class: "d-block product-image") %>
          </div>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#product-carousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#product-carousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    <h2 class="card-subtitle product-full-price"><%= price(product.price) %></h2>
    <hr/>
    <span><%= product.description %></span>
    <hr/>
    <%= form_with model: BasketLine.new, url: basket_lines_path, class: "add-form product-full-add" do |f| %>
      <%= f.hidden_field :product_id, value: product.id %>
      <%= f.hidden_field :basket_id, value: basket_id %>
      <%= f.submit t(:add), class: "add-submit" %>
      <%= f.number_field :quantity, value: 1, class: "add-number" %>
      <%= f.submit t(:to_basket), class: "add-submit" %>
    <% end %>
  </div>
</div>

app/views/products/_line.html.erb
<%= link_to product.name, product_path(product), class: "product-link" %>
-
<%= price(product.price) %>


<%= form_with model: line, url: basket_line_path(line) do |f| %>
  <%= f.hidden_field :product_id, value: line.product_id %>
  <%= f.hidden_field :basket_id, value: line.basket_id %>
  <%= f.label t(:quantity) %>
  <%= f.number_field :quantity, value: line.quantity, class: "edit-number rounded" %>
  <%= f.submit t(:change), class: "btn btn-secondary" %>
  <%= f.submit t(:remove), class: "btn btn-danger" %>
<% end %>
total:
<%= price(line.line_amount) %><br/>

app/views/products/_new.html.erb
<div id="newProduct" class="collapse" data-parent="#content">
  
  <%= form_with model: product, url: seller_products_path(@seller), id: "new_product", html: { class: "form-dashboard d-flex flex-column align-items-start bg-light rounded-lg" } do |f| %>

    <div class="form-group form-dashboard-field">
      <%= f.label :category, t(:category), class: "label-dashboard" %>
      <%= f.select(:category, options_for_select(Category.all_as_hash[params['locale']]), {}, { class: "form-control input-dashboard" }) %>
    </div>

    <div class="form-group form-dashboard-field">
      <%= f.label :name, t(:name), class: "label-dashboard" %>
      <%= f.text_field :name, class: "form-control input-dashboard" %>
    </div>

    <div class="form-group form-dashboard-field">
      <%= label_tag :en, t(:available_en), class: "label-dashboard" %>
      <%= check_box_tag :new_product_en, :en, false, class: "check-dashboard" %>
    </div>

    <div class="form-group form-dashboard-field">
      <%= f.label :description, t(:description_en), class: "label-dashboard" %>
      <%= f.text_field :description, class: "form-control input-dashboard" %>
    </div>
    
    <% I18n.non_default_locales_hash.each do |sym, string| %>
      <div class="form-group form-dashboard-field">
        <%= label_tag sym, t(:available) + t(string), class: "label-dashboard" %>
        <%= check_box_tag "new_product_" + sym.to_s, sym, false, class: "check-dashboard" %>
      </div>

      <%= f.fields_for :product_translations do |trans| %>
        <div class="form-group form-dashboard-field">
          <%= trans.label :description, t(:description) + " " + t(string), class: "label-dashboard" %>
          <%= trans.text_field :description, class: "form-control input-dashboard" %>
          <%= trans.hidden_field :lang, value: sym %>
        </div>
      <% end %>
    <% end %>

    <%= f.hidden_field :translations, value: "" %>

    <div class="form-group form-dashboard-field">
      <%= f.label :price, t(:price), class: "label-dashboard" %>
      <%= f.number_field :price, class: "form-control input-dashboard" %>
    </div>

    <div class="form-group form-dashboard-field">
      <%= f.label :price_excl_vat, t(:price_excl_vat), class: "label-dashboard" %>
      <%= f.number_field :price_excl_vat, class: "form-control input-dashboard" %>
    </div>

    <div id="new_product_tags_english" style="display:none;">
      <div class="form-group d-flex flex-column form-dashboard-field">
        <%= f.fields_for :product_tags do |tags| %>
          <div class="d-flex">
            <%= tags.label :tag, t(:tag) + " " + t(:english), class: "label-dashboard" %>
            <%= tags.text_field :tag, class: "form-control input-dashboard tag-dashboard" %>
            <%= tags.hidden_field :lang, value: "en" %>
          </div>
        <% end %>
      </div>
    </div>

    <% I18n.non_default_locales_hash.each do |sym, string| %>
      <div id="new_product_tags_<%= string %>" style="display:none;">
        <div class="form-group d-flex flex-column form-dashboard-field">
          <%= f.fields_for :product_tags do |tags| %>
            <div class="d-flex">
              <%= tags.label :tag, t(:tag) + " " + t(string), class: "label-dashboard" %>
              <%= tags.text_field :tag, class: "form-control input-dashboard tag-dashboard" %>
              <%= tags.hidden_field :lang, value: sym.to_s %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>

    <div class="form-group form-dashboard-field">
      <%= f.label :cover, t(:cover), class: "label-dashboard" %>
      <%= f.file_field :cover, class: "file-dashboard" %>
    </div>

    <div class="form-group form-dashboard-field">
      <%= f.label :images, t(:images), class: "label-dashboard" %>
      <%= f.file_field :images, multiple: true, class: "file-dashboard" %>  
    </div>

    <%= f.hidden_field :seller_id, value: @seller.id %>
    
    <div class="action submit-dahsboard">
      <%= f.submit t(:create), class: "btn btn-dark" %>
    </div>
  <% end %>
</div>

<script type='text/javascript'>
  var new_product_en = document.getElementById('new_product_en'), 
    new_product_fr = document.getElementById('new_product_fr'),
    new_product_hidden = document.getElementById('product_translations'),
    new_product_tags_en = document.getElementById('new_product_tags_english'),
    new_product_tags_fr = document.getElementById('new_product_tags_french');

  new_product_en.addEventListener('change', function() {
    if(this.checked) {
        new_product_hidden.value = new_product_hidden.value += "|en"
        new_product_tags_en.style.display = 'inline-flex'
    } else {
        new_product_hidden.value = new_product_hidden.value.replace("en", "")
        new_product_tags_en.style.display = 'none'
    }
  }, false);

  new_product_fr.addEventListener('change', function() {
    if(this.checked) {
        new_product_hidden.value = new_product_hidden.value += "|fr"
        new_product_tags_fr.style.display = 'inline-flex'
    } else {
        new_product_hidden.value = new_product_hidden.value.replace("fr", "")
        new_product_tags_fr.style.display = 'none'
    }
  }, false);
</script>

app/views/products/index.html.erb
<%= render 'nav/top' %>

<%= render 'nav/catalogue_toolbar', locals: { categories: @categories } %>

<%= render partial: 'layouts/presenter', locals: { presentee: @presentee } if params['action'] == "index_seller" || params['action'] == "index_category" %>

<% @products.each do |product| %>
  <%= render partial: 'products/card', locals: { product: product, basket_id: @current_basket.id } %>
<% end %>

<%= render 'nav/catalogue_pagination' %>

<%= render 'nav/footer' %>

app/views/products/new.html.erb
<span>New Product</span>

<%= form_for [:seller, @product] do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
  <%= f.label :category, "Category" %>
  <%= f.text_field :category %>
  <%= f.label :key_words, "Key words" %>
  <%= f.text_field :key_words %>
  <%= f.label :description, "Description" %>
  <%= f.text_field :description %>
  <%= f.label :price, "Price" %>
  <%= f.text_field :price %>
  <%= f.hidden_field :seller_id, value: @seller_id %>
  <%= f.submit "Create" %>
<% end %>

app/views/products/show.html.erb
<%= render 'nav/top' %>

<%= render 'nav/catalogue_toolbar', locals: { categories: @categories } %>

<%= render partial: 'layouts/presenter', locals: { presentee: @seller } %>

<%= render partial: 'products/full', locals: { product: @product, basket_id: @current_basket.id } %>

<%= render 'nav/footer' %>