config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    #home
    root to: 'home#index'
    get '/about', to: 'home#about', as: 'about'
    get '/contact', to: 'home#contact', as: 'contact'
    get '/photos', to: 'home#photos', as: 'photos'
    get '/resume', to: 'home#resume', as: 'resume'
    get '/download_resume', to: "home#download_resume", as: 'download_resume'

    #DEVISE:
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    devise_for :clients, controllers: { registrations: 'client/registrations', sessions: 'client/sessions' }

    devise_for :sellers, controllers: { registrations: 'seller/registrations', sessions: 'seller/sessions' }, path_names: { registration: ENV['NEW_SELLER_PATH'] }

    #DASHBOARDS:
    get "c/:id/dashboard" => 'dashboard_clients#show', as: :client_dashboard
    resources :clients, path: "c", only: [:update, :destroy] do
      resource :basket, only: :edit, path: "checkout"
      resources :basket_lines, only: :update, path: "b"
      resources :locations, only: [:create, :update, :destroy], path: "l"
    end

    get "s/:id/dashboard" => 'dashboard_sellers#show', as: :seller_dashboard
    resources :sellers, path: "s", only: [:update] do
      member { patch 'update_cover'}
      member { patch 'attach_image'}
      member { patch 'delete_image'}
      resources :products, only: [:create, :update, :destroy], path: "p" do
        member { patch 'update_cover'}
        member { patch 'attach_image' }
        member { patch 'delete_image' }
      end
      resources :locations, only: [:create, :update, :destroy], path: "l"
    end

    #CATALOGUE:
    resources :products, only: :show

    get '/catalogue(/:page)', to: 'products#index', as: 'catalogue'
    get '/s/:id(/:page)', to: 'products#index_seller', as: 'c_seller'
    get '/c/:id(/:page)', to: 'products#index_category', as: 'c_category'

    #CHECKOUT
    resources :baskets, only: :show
    resources :basket_lines, only: [:create, :update]

    resources :orders, only: [:create]

    # concern :manageable do
    #   resources :conversations, :orders...
    # end
  end
end

app/views/nav/_catalogue_pagination.html.erb
<nav aria-label="Page navigation example" class="d-flex justify-content-center">
  <ul class="pagination">
    <% @pages_urls.each do |page| %>
      <li class="page-item <%= page[:class] %>">
        <%= link_to page[:text], page[:link], class: "page-link" %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/nav/_catalogue_toolbar.html.erb
<nav class="navbar sticky-top navbar-expand-md navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= t(:categories) %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to t(:all_cat), catalogue_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <% @categories.each do |category| %>
            <%= link_to category[0], c_category_path(category[0]), class: "dropdown-item" %>
          <%end%>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= t(:sellers) %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to t(:all_sel), catalogue_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <% @sellers.each do |seller| %>
            <%= link_to seller.name, c_seller_path(seller.slug), class: "dropdown-item" %>
          <%end%>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= t(:tags) %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to t(:all_tag), catalogue_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <% @tags.each do |tag| %>
            <%= link_to tag, catalogue_path(tag: tag), class: "dropdown-item" %>
          <%end%>
        </div>
      </li>
    </ul>
    <%= form_with(url: catalogue_path, method: "get", local: true, class: "form-inline my-2 my-lg-0") do %>
      <%= text_field_tag(:q, nil, class: "form-control mr-sm-2") %>
      <%= submit_tag(t(:search), class: "btn btn-outline-primary my-2 my-sm-0") %>
    <% end %>
  </div>
</nav>

app/views/nav/_footer.html.erb
<nav class="navbar navbar-light bg-light fixed-bottom">
  <span>
    <%= t(:seller) %>:
    <% if seller_signed_in? %>
      <%= link_to t(:log_out), destroy_seller_session_path, method: :delete %>
      |
      <%= link_to t(:account), seller_dashboard_path(current_seller) %>
    <% else %>
      <%= link_to t(:sign_in), new_seller_session_path %>
    <% end%>
  </span>

  <% if admin_user_signed_in? %>
    <%= link_to t(:admin_log_out), destroy_admin_user_session_path, method: :delete %>
  <% end %>

  <span style="color:#2ab7ca;">
  <%= link_to t(:resume), resume_path %>
  |
  <%= link_to t(:photos), photos_path %>
  |
  <%= mail_to "jcbelouard@gmail.com" %>
  </span>
</nav>

app/views/nav/_nav_top.html.erb
<%= link_to t(:sign_up), new_client_registration_path %>
  <% if client_signed_in? %>
    <%= link_to t(:log_out), destroy_client_session_path, method: "delete" %>
    <%= link_to t(:account), client_dashboard_path(current_client) %>
  <% else %>
    <%= link_to t(:sign_in), new_client_session_path %>
  <% end%>
  <%= link_to t(:checkout), edit_basket_path %>
  <% if I18n.locale == :en %>
    <%= link_to "fr", { locale: 'fr' } %>
  <% else %>
    <%= link_to "en", { locale: 'en' } %>
  <%end%>

app/views/nav/_top.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light d-flex align-items-baseline">
  <%= link_to t(:home), root_path, class: "navbar-brand" %>
  <span class="card-subtitle"><%= t(:subtitle) %></span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item btn btn-outline-primary btn-sm">
        <%= link_to t(:sign_up), new_client_registration_path %>
      </li>
      <% if client_signed_in? %>
        <li class="nav-item btn btn-outline-primary btn-sm">
          <%= link_to t(:log_out), destroy_client_session_path, method: "delete" %>
        </li>
        <li class="nav-item btn btn-outline-primary btn-sm">
          <%= link_to t(:account), client_dashboard_path(current_client) %>
        </li>
      <% else %>
        <li class="nav-item btn btn-outline-primary btn-sm">
          <%= link_to t(:sign_in), new_client_session_path %>
        </li>
      <% end %>
      <li class="nav-item btn btn-outline-primary btn-sm">
        <%= link_to t(:basket), basket_path(@current_basket) %>
      </li>
      <% if I18n.locale == :en %>
        <li class="nav-item btn btn-outline-danger btn-sm">
          <%= link_to image_tag("icons/fr.png", size: "20x14"), { locale: 'fr' } %>
        </li>
      <% else %>
        <li class="nav-item btn btn-outline-danger btn-sm">
          <%= link_to image_tag("icons/en.png", size: "20x16"), { locale: 'en' } %>
        </li>
      <%end%>
    </ul>
  </div>
</nav>
<%= render partial: 'layouts/alerts' %>